#!/bin/bash

if [ ${#@} -eq '0' ];
then
	printf 'usage:
-u: u print UDP ports that are listening.
-t: t print TCP portst that are listening.\n\n'

fi

while getopts ":u:t" opt; do
	case $opt in
		u) echo "UDP ports that are listening:" 
		   netstat -lu
		;;
		
		t) printf "TCP ports that are listening:"
		   netstat -lt
		;;
	esac
done
