#!/bin/bash

if [ ${#@} -eq '0' ];
then
	printf 'usage:
-f = -f path to file.
'
fi

disk_percentage() {
	local fileSize=`wc -c $1 | awk '{ print $1 }'`
	local diskSize=`df -l | grep \/$ | awk '{ print $2}'`
	
	awk -v file="$fileSize" -v disk="$diskSize" -f <(cat - <<- 'EOD'
	BEGIN {
		filekb = file/1000
		print filekb/disk " % disk space"
	}
EOD
)
	echo $scriptVariable
}


while getopts "f:a:" opt; do
	case ${opt} in
		f) 
			echo $OPTARG " uses: "
			disk_percentage $OPTARG
		;;
		a) 
			echo "screw $OPTARG"
		;;
	esac
done

