#!/bin/bash

RED='\033[0;31m'
ORANGE='\033[0;33m'
GREEN='\033[0;32m'
NC='\033[0m'

DISKPERCENTAGE_LIMIT='80'

cpustats() {
  local MODEL=`grep -E -m1 'model\sname' /proc/cpuinfo | cut -d ":" -f2 | sed -E 's/^\s+//g'`
  local VENDOR=`grep -E -m1 'vendor_id' /proc/cpuinfo | awk '{print $3}'`
  local CORES=`grep -E -m1 'cpu\scores\b' /proc/cpuinfo | awk '{print $4}'`
  local CACHE=`grep -E -m1 'cache\ssize\b' /proc/cpuinfo | awk '{print $4}'`
  local CURRENT_CORE_SPEED=`grep -E 'cpu\s+MHz\b' /proc/cpuinfo | awk '{print $4}' | tr -s '\n' " "`

  echo -e "${ORANGE}Model: ${GREEN}$MODEL${NC}"
  echo -e "${ORANGE}Vendor: ${GREEN}$VENDOR${NC}"
  echo -e "${ORANGE}Number of physical Cores: ${GREEN}$CORES${NC}"
  echo -e "${ORANGE}Core Cache Size: ${GREEN}$CACHE${NC}"
  echo -e "${ORANGE}Current Core speed: ${GREEN}$CURRENT_CORE_SPEED${NC}"
}

diskcheck() {
  local DISKDRIVEINFO=`sudo fdisk -l | grep Disk`
  local HARDDISKID=`printf "$DISKDRIVEINFO" | grep -E '\/dev\/sd.*' | awk '{print $2}' | tr -d ':'`
  local TOTALDISKCAP=`printf "$DISKDRIVEINFO" | grep -E '\/dev\/sd.*' | awk '{print $3}'`
  local DISKMFG=`printf "$DISKDRIVEINFO" | grep -E 'Disk\s+model\:' | cut -d ':' -f2`

  echo -e "${ORANGE}Disk identifier: ${GREEN}$HARDDISKID${NC}"
  echo -e "${ORANGE}Total Disk Capacity: ${GREEN}$TOTALDISKCAP${NC}"
  echo -e "${ORANGE}Disk Manufacturer: ${GREEN}$DISKMFG${NC}"
}

diskusage() {
  echo -e "${ORANGE}\nDisk Usage${NC}"
  local DISKINFO=`df -h --output=target,used,avail,pcent`

  IFS=$'\n'
  local DISKARR=($DISKINFO)

  for i in "${DISKARR[@]}"
  do
    if [[ `echo $i | awk '{print $4}' | tr -d '%'` -gt $DISKPERCENTAGE_LIMIT ]]; then
      echo -e "${RED}$i ${ORANGE}Disk utilization dangerously high. Check filesystem.${NC}"
    else
      echo -e "${GREEN}$i${NC}"
    fi
  done
}

memstats() {
  local TOTALRAM=`cat /proc/meminfo | grep -E -m1 'MemTotal' | awk '{ print $2/1000000}'`
  local AVAILABLERAM=`cat /proc/meminfo | grep -E -m1 'MemAvailable' | awk '{ print $2/1000000}'`

  echo -e "\nAvailable memory: ${GREEN}$AVAILABLERAM${NC}"
  echo -e "Total Memory: ${ORANGE}$TOTALRAM${NC}"
}

ramhardware() {
  local MEMINFO=$(sudo dmidecode -t memory)
  local RAMSLOTS=`printf "$MEMINFO\n" | grep -E 'Number\sOf\sDevices' | awk '{print $4}'`
  local FORMFACTOR=($(printf "$MEMINFO\n" | grep -E 'Form\sFactor' | awk '{print $3}'))
  local SIZE=($(printf "$MEMINFO\n" | grep -E 'Size' | awk '{print $2}'))
  local TYPE=($(printf "$MEMINFO\n" | grep -E '^\s+Type\:' | awk '{print $2}'))
  local MFG=($(printf "$MEMINFO\n" | grep -E '^\s+Manufacturer\:' | awk '{print $2}'))

  echo -e "${ORANGE}Ram Slots: ${GREEN}$RAMSLOTS${NC}\n"

  for i in {0,1};
  do
    echo -e "${ORANGE}Slot: ${GREEN}$i${NC}"
    echo -e "${ORANGE}Size (MB): ${GREEN}${SIZE[$i]}${NC}"
    echo -e "${ORANGE}Form Factor: ${GREEN}${FORMFACTOR[$i]}${NC}"
    echo -e "${ORANGE}Slot Type: ${GREEN}${TYPE[$i]}${NC}"
    echo -e "${ORANGE}Manufacturer: ${GREEN}${MFG[$i]}${NC}\n"
  done
}

helpme() {
  printf "${ORANGE}Description: This will get hardware information about the system
usage: resources <option>
options:${NC} 
  ${GREEN}--cpu)${NC} ${ORANGE}prints out cpu information of the system${NC}
  ${GREEN}--ram)${NC} ${ORANGE}prints out information of ram on system${NC}
  ${GREEN}--disk)${NC} ${ORANGE}prints out information of disk volumes on system${NC}
  ${GREEN}--net)${NC} ${ORANGE}prints out information of network adapters on system${NC}
"
}

networkhardware() {
  local DEVICEINFO=`lspci`
  local WIFIDEVICE=`echo -e "$DEVICEINFO" | grep -E 'Network\s+controller' | cut -d ':' -f3 | cut -d '(' -f1 | sed -E 's/^[ \t]*|[ \t]*$//g'`
  local ETHERNETDEVICE=`echo -e "$DEVICEINFO" | grep -E 'Ethernet\s+controller' | cut -d ':' -f3 | cut -d '(' -f1 | sed -E 's/^[ \t]*|[ \t]*$//g'`

  echo -e "${ORANGE}WiFi: ${GREEN}$WIFIDEVICE${NC}" 
  echo -e "${ORANGE}Ethernet: ${GREEN}$ETHERNETDEVICE${NC}" 
}

case $1 in
  --cpu)
    cpustats
  ;;

  --disk)
    diskcheck
    diskusage
  ;;
  
  --ram)
    memstats
    ramhardware
  ;;
  --net)
    networkhardware
  ;;

  *)
    helpme
esac
