#!/bin/bash

RED='\033[0;31m'
ORANGE='\033[0;33m'
GREEN='\033[0;32m'
NC='\033[0m'

CURRENTDIR=`dirname $0`

echo -e "${ORANGE}Scripts available${NC}\n"

SCRIPTS=`ls -1 $CURRENTDIR | grep -v 'scriptlist'`

echo -e "${GREEN}$SCRIPTS${NC}"
echo -e "\n${ORANGE}End Scripts${NC}"
